[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_swap_contract = "45z9sEr41LLWyuEdAJmxtoV1R7dNuR6h69cE6ZiSN845"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/koutrou172/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
